modLoader="javafml"
loaderVersion="[${forge_version},)"

[[mods]]
    modId="${mod_id}"
    displayName="${mod_name}"
    description="${mod_description}"
    version="${mod_version}"
    displayURL="${mod_url}"
    authors="${mod_author}"

[[dependencies.consolehud]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.consolehud]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},)"
    ordering="NONE"
    side="BOTH"